practice the application of numpy

In [1]:
#importnumpy
import numpy as np

In [ ]:
# create a numpy array and do some basic calculumn
m = np.array([1,2,3])
n = np.array([4.0,5.0,6.0])
print(m+n)
print(m*n)
print(m/n)
print(m/2.0)


[5. 7. 9.]
[ 4. 10. 18.]
[0.25 0.4  0.5 ]
[0.5 1.  1.5]


In [9]:
#create a numpy matrix
A = np.array([[1,2],[3,4]])
print(A.shape)
print(A.dtype)
print(A)

(2, 2)
int64
[[1 2]
 [3 4]]


In [10]:
B = np.array([[4,5],[6,7]])
print(A+B)
print(A*B)

[[ 5  7]
 [ 9 11]]
[[ 4 10]
 [18 28]]


In [ ]:
# about broadcast
M = np.array([[1,2],[3,4]])
N = np.array([10,20])
N1 = np.array([[10],[20]])
print(M*N) 
print(M*N1)

[[10 40]
 [30 80]]
[[10 20]
 [60 80]]


In [ ]:
#how about A*B
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[1,2,3],[4,5,6]])
print(A@B)
print(np.dot(A,B))
print(np.matmul(A,B))


[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [19]:
#then about Transpose
A_T = A.T
print(A_T)
A_t = np.transpose(A)
print(A_t)

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


In [29]:
#then comes to index
X = np.array([[1,2,5],[2,1,6],[4,4,89]])
print(X)
print(X[0])
print(X[1][2])
print(X[1,2])


[[ 1  2  5]
 [ 2  1  6]
 [ 4  4 89]]
[1 2 5]
6
6


In [26]:
print(X[1,:])
print(X[:,0])

[2 1 6]
[1 2 4]


In [28]:
print(X[:2,1:3])

[[2 5]
 [1 6]]


In [ ]:
m = np.arange(len(X))
n = np.array([0,2,1])
print(X[m,n])
#相当于是去找坐标

[1 6 4]


In [24]:
X = X.flatten()
print(X)
print(X[np.array([0,2,4])])
print(X>15)
print(X[X>15])

[ 1  2  5  2  1  6  4  4 89]
[1 5 1]
[False False False False False False False False  True]
[89]


In [31]:
# about sum beyond dimensions
A = np.array([[1,2],[3,4]])
print(A)
print(np.sum(A))
print(np.sum(A,axis = 0))
print(np.sum(A,axis=1))


[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [37]:
# some upgraded knowledge
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
add = np.tile(b,(2,2))#represent复制几行几列
add1 = np.tile(a,(2,4))
print(add)
print(add1)

[[5 6 5 6]
 [5 6 5 6]]
[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


In [38]:
#change dimensions
x = np.reshape(add,(4,2))
print(x)

[[5 6]
 [5 6]
 [5 6]
 [5 6]]


In [53]:
#delete dimensions
x = np.array([[[1,2,1],[1,2,1]]])
print(x.shape)
y = np.squeeze(x,0)
print(y)
print(y.shape)

(1, 2, 3)
[[1 2 1]
 [1 2 1]]
(2, 3)


In [54]:
#add dimensions
z = np.expand_dims(y,1)
print(z)
print(z.shape)

[[[1 2 1]]

 [[1 2 1]]]
(2, 1, 3)


In [46]:
#some interesting functions
a = np.zeros((2,3))
b = np.ones((3,2))
c = np.eye((4))
d = np.random.random((2,1))
#attention two slice of ()
print(a)
print(b)
print(c)
print(d)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.19970089]
 [0.03180948]]
